Part-3 Payment/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from . forms import UserLoginForm, PwdResetForm, PwdResetConfirmForm
from . import views

app_name = "account"
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/registration/login.html',
                                                form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/',
         views.account_activate, name='activate'),
    # Reset password
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/user/password_reset_form.html",
                                                                 success_url='/password_reset_email_confirm',
                                                                 email_template_name='account/user/password_reset_email.html',
                                                                 form_class=PwdResetForm), name='password_reset'),
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='account/user/password_reset_confirm.html',
                                                                                                success_url='/account/password_reset_complete/',
                                                                                                form_class=PwdResetConfirmForm),
         name="password_reset_confirm"),
    path('password_reset_complete/',
         TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_complete'),
    # User dashboard
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/edit/', views.edit_details, name='edit_details'),
    path('profile/delete_user/', views.delete_user, name='delete_user'),
    path('profile/delete_confirm/', TemplateView.as_view(
        template_name="account/user/delete_confirm.html"), name='delete_confirmation'),
]

Part-3 Payment/store/urls.py
from django.urls import path
from . import views

app_name = 'store'
urlpatterns = [
    path('', views.product_all, name='product_all'),
    path('<slug:slug>/', views.product_detail, name='product_detail'),
    path('category/<slug:category_slug>/',
         views.category_list, name='category_list'),
]

Part-3 Payment/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
    {% block title %}
        
    {% endblock title %}
        </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.7.0.min.js" integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    {% comment %} <link rel="stylesheet" href="{% static 'core/css/base.css' %}"> {% endcomment %}
    <link rel="stylesheet" href="{% static 'basket/css/basket.css' %}">
  </head>
  <body>
    <header>
        <nav class="navbar navbar-expand-sm bg-body-tertiary">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Mineralpedia</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Contact</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Gallery
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="{% url 'store:product_all' %}">All Categories</a></li>
                      {% for c in categories %}
                        <li {% if category.slug == c.slug %}class="selected" {% endif %}>
                          <a class="dropdown-item" href="{% url 'store:category_list' c.slug %}">{{ c.name|title }}</a>
                        </li>
                      {% endfor %}
                    </ul>
                  </li>
                </ul>

                {% comment %} <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <div>
                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                            class="bi bi-list" viewBox="0 0 16 16">
                            <path fill-rule="evenodd"
                                d="M2.5 11.5A.5.5 0 0 1 3 11h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 7h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 3h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z" />
                        </svg>
                    </div>
                    <span class="fs15 fw500">Shop</span>
                </button> {% endcomment %}

                {% if user.is_authenticated %}
                  <a type="button" role="button" href="{% url 'account:logout' %}"
                      class="btn btn-outline-secondary border-0 basket-btn">
                      <div>
                          <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                              class="bi bi-door-closed" viewBox="0 0 16 16">
                              <path
                                  d="M3 2a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v13h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V2zm1 13h8V2H4v13z" />
                              <path d="M9 9a1 1 0 1 0 2 0 1 1 0 0 0-2 0z" />
                          </svg>
                      </div>
                      <span class="fs15 fw500">Logout</span>
                  </a>
                {% else %}
                  <a type="button" role="button" href="{% url 'account:login' %}"
                      class="btn btn-outline-secondary border-0 basket-btn">
                      <div>
                          <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                              class="bi bi-door-closed" viewBox="0 0 16 16">
                              <path
                                  d="M3 2a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v13h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V2zm1 13h8V2H4v13z" />
                              <path d="M9 9a1 1 0 1 0 2 0 1 1 0 0 0-2 0z" />
                          </svg>
                      </div>
                      <span class="fs15 fw500">Login</span>
                  </a>
                {% endif %}

                <a type="button" role="button" href="{% url "account:dashboard" %}"
                  class="btn btn-outline-secondary border-0 basket-btn">
                  <div>
                      <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                          class="bi bi-person" viewBox="0 0 16 16">
                          <path
                              d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z" />
                      </svg>
                  </div>
                  <span class="fs15 fw500">Account</span>
                </a>

                <a type="button" role="button" href="{% url 'basket:basket_summary' %}"
                    class="btn btn-outline-secondary border-0 basket-btn">

                    {% with total_qty=basket|length %}
                    <div id="basket-qty" class="basket-qty">
                        {% if total_qty > 0 %}
                        {{ total_qty }}
                        {% else %}
                        0
                        {% endif %}
                    </div>
                    {% endwith %}
                    <div>
                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                            class="bi bi-cart3" viewBox="0 0 16 16">
                            <path
                                d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                        </svg>
                    </div>
                    <span class="fs15 fw500">Basket</span>
                </a>
              </div>
              
              {% comment %} <div class="d-md-none d-lg-none d-xl-none">
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li><a class="dropdown-item" href="{% url "store:product_all" %}">All</a></li>
                        {% for c in categories %}
                        <li {% if category.slug == c.slug %}class="selected" {% endif %}>
                            <a class="dropdown-item" href="{% url 'store:category_list' c.slug %}">{{ c.name|title }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
              </div> {% endcomment %}
              <form class="d-flex w-100 d-md-none">
                <input class="form-control me-2" type="search" placeholder="Search products or FAQ"
                    aria-label="Search">
                <button class="btn btn-outline-secondary" type="submit">Search</button>
              </form>

            </div>
        </nav>
    </header>
    <div class="container">
    {% block contents %}
        
    {% endblock contents %}
    </div>
  </body>
</html>